<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enviar cdigo</name>
   <tag></tag>
   <elementGuidId>7c0873b3-3aef-48b0-bb42-80ccfe59540f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSendCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSendCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd9830da-d5e7-4792-ac31-4eb824f57c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSendCode</value>
      <webElementGuid>892d27bd-9732-4edd-bf0c-931ef1cd3769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>831f6a69-412c-464a-a78f-62e1582ab116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enviar código</value>
      <webElementGuid>74adaa33-c506-4e39-a4fd-787a7e2df59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSendCode&quot;)</value>
      <webElementGuid>32c3efd2-b5b8-4a83-abe9-5b2b5900eb8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSendCode']</value>
      <webElementGuid>9e6d46d7-c4b4-419c-a1ce-73edb3d149fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormularioLoginContainer']/div[2]/form/div[3]/button</value>
      <webElementGuid>9183d4c6-86dd-4b7f-9112-12416d5035d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::button[1]</value>
      <webElementGuid>545b0630-f97c-4b48-a236-0d86e31c2f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte'])[1]/following::button[1]</value>
      <webElementGuid>d079b4df-992f-4642-8cda-eb24f71ba528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[2]/preceding::button[1]</value>
      <webElementGuid>b1c72ab3-eaaf-45db-840c-b6425f92faea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eventos'])[2]/preceding::button[1]</value>
      <webElementGuid>712b7e8a-705c-4b42-820c-38fc90eb62ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enviar código']/parent::*</value>
      <webElementGuid>f2e2ce61-ee88-4923-9a0e-e57e8a93ff4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d007c51e-a95b-47e9-92f0-20b32b3cfbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSendCode' and @type = 'submit' and (text() = 'Enviar código' or . = 'Enviar código')]</value>
      <webElementGuid>7e1ff982-8791-4ef0-a877-7eb21e235f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
