<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Registrarse</name>
   <tag></tag>
   <elementGuidId>fe68e34e-587d-49df-a834-0415d6aca0ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.buttonRegister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d169c95-b44a-42de-a764-c6fc8c29f624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonRegister</value>
      <webElementGuid>eecb6087-6416-429d-8e79-2868e7f65d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b49b221-146c-459f-8616-6da5114f998d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registrarse</value>
      <webElementGuid>fe01a18a-eef1-4dff-a6f9-036a1d3f5bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormularioLoginContainer&quot;)/div[@class=&quot;bloque2&quot;]/form[@class=&quot;form1&quot;]/div[@class=&quot;buttons&quot;]/div[@class=&quot;botonesLogincontainer&quot;]/a[1]/button[@class=&quot;buttonRegister&quot;]</value>
      <webElementGuid>0f0ddf2c-82b0-4292-99b6-3abc0108e9cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>0a95e8c7-9597-4e1c-a615-f6553e7bbf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormularioLoginContainer']/div[2]/form/div[3]/div/a/button</value>
      <webElementGuid>9962d36e-f230-4acb-a8cf-021d0c42b178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acceder'])[1]/following::button[1]</value>
      <webElementGuid>70174638-cabe-42d5-83d1-461080586320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::button[2]</value>
      <webElementGuid>839d4949-4dd9-4380-8c16-d8c714ef5a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste tu contraseña?'])[1]/preceding::button[1]</value>
      <webElementGuid>379952ed-f16c-4000-9312-f510c9f8bbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[2]/preceding::button[2]</value>
      <webElementGuid>d2cb79a0-c370-4d44-9160-250c855acd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registrarse']/parent::*</value>
      <webElementGuid>e855893b-226c-4547-ae34-ee711b3d3ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>93202f5c-2d6b-4807-bf41-43312335c4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Registrarse' or . = 'Registrarse')]</value>
      <webElementGuid>e7749093-a17d-4db7-984a-228f2b1b2c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
