<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Configuracin de tu Perfil</name>
   <tag></tag>
   <elementGuidId>d17ddb76-7bbd-4975-8c09-e6c7c19a0f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.TituloPerfil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8b264770-927a-4efb-9d94-89d9186c89e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TituloPerfil</value>
      <webElementGuid>b45b73f0-8a0f-4baa-b656-f081518da695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configuración de tu Perfil</value>
      <webElementGuid>cc3d00ad-3388-4e93-9e27-e0e14607d613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PerfilContainer&quot;]/h2[@class=&quot;TituloPerfil&quot;]</value>
      <webElementGuid>5340d86a-5293-4660-a3ec-08e4b35b1cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/h2</value>
      <webElementGuid>4c5e4d24-e18d-4adb-8987-ab43a396e95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte'])[1]/following::h2[1]</value>
      <webElementGuid>bada41dc-64a2-46cf-8f10-cec9264355d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eventos'])[1]/following::h2[1]</value>
      <webElementGuid>e78e6530-69c2-46cc-9713-6027e7319a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DON.Ar'])[1]/preceding::h2[1]</value>
      <webElementGuid>773488d2-b493-4fcf-ba07-ea44bdd2ffdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donaciones que recibe'])[1]/preceding::h2[1]</value>
      <webElementGuid>658b8cd9-50b4-4d66-a78e-f0996645833d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Configuración de tu Perfil']/parent::*</value>
      <webElementGuid>1f0edd8f-42e5-4987-98c4-93c37e83e244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>5a595c9f-9109-46d1-8607-59415390285b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Configuración de tu Perfil' or . = 'Configuración de tu Perfil')]</value>
      <webElementGuid>2d819c23-a9e5-44fc-a62d-b451bf7cfbf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DON.AR'])[1]/preceding::h2[1]</value>
      <webElementGuid>5cb39144-b87c-4dc1-b729-7e7914ef79ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestión de cuenta'])[1]/preceding::h2[1]</value>
      <webElementGuid>f4d456cf-8e38-4746-b954-741797232c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correo Electrónico'])[1]/preceding::h2[1]</value>
      <webElementGuid>e2cd9f87-0f59-499c-9fcd-0b2f16b25ece</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
