<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Soporte_LogOutIcon</name>
   <tag></tag>
   <elementGuidId>3818947f-a51e-4ea0-82e2-4cd7cbb3cdd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.LogOutIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='BotonContainer']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>692dca33-29c5-41a2-bae3-8693a6dbff29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/log-in-outline.1603d9cf952a00597e4a008cbbfdb2cb.svg</value>
      <webElementGuid>cda614bb-7f66-46d9-8c2f-3447d070a8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cerrar Sesion</value>
      <webElementGuid>9221163a-8dc9-46ac-a095-211b246c6b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LogOutIcon</value>
      <webElementGuid>8e52863d-93b9-4e33-9ccd-5a1cefe3206c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BotonContainer&quot;)/img[@class=&quot;LogOutIcon&quot;]</value>
      <webElementGuid>26afe155-7d39-460d-a308-7c47bceb827f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='BotonContainer']/img</value>
      <webElementGuid>1d37e726-6c34-45e3-9555-3d3e8e50e59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cerrar Sesion']</value>
      <webElementGuid>2cc436e1-243c-4248-bc05-cc096891dd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>26c78178-e736-437a-8810-f61550a8f5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/log-in-outline.1603d9cf952a00597e4a008cbbfdb2cb.svg' and @alt = 'Cerrar Sesion']</value>
      <webElementGuid>082fae29-c777-43ff-a9b0-903c110e7b0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
