<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_input-field</name>
   <tag></tag>
   <elementGuidId>2164b976-42f3-4011-aa5e-3a5a4b442145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.input-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>032dd868-344e-4c05-82d1-d780e4ee9e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b1a7b454-01db-4ac9-b0ff-49602fafb2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Correo Electrónico</value>
      <webElementGuid>6482f920-1966-4aed-b509-79dc229f4a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>df5a05eb-c75a-4d31-8519-71991bf53b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96f058ce-812d-4eca-bdcb-7e75f47391d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormularioLoginContainer&quot;)/div[@class=&quot;bloque2&quot;]/form[@class=&quot;form1&quot;]/div[@class=&quot;field&quot;]/input[@class=&quot;input-field&quot;]</value>
      <webElementGuid>8dc87b76-ecbb-4c55-9dec-a71771b948e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>f35943d6-14d9-4482-a8dc-fa2988fb3b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FormularioLoginContainer']/div[2]/form/div/input</value>
      <webElementGuid>c668f5f2-ff0d-486c-8175-bd7cf533f1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d0bddffd-9835-4d9c-b8be-69d7bb5615cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Correo Electrónico' and @type = 'text']</value>
      <webElementGuid>159a193e-9a79-4ae0-bace-ae16e69af3df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
