<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_description</name>
   <tag></tag>
   <elementGuidId>7742f335-2028-4040-9982-74c439b7afcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdc2552b-e5d6-4461-beda-942eb4eb932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>a1cdc432-c7ee-4d0f-b6fc-2ab7b595e923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24cd7aa1-098c-4d7e-89ec-87efd3a5fd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>389dc5f1-5e43-4edd-9bff-eb1b6498602c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>¿Por qué necesitan la visibilidad?</value>
      <webElementGuid>4a510ae9-e293-44d1-8148-20f8e423d51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>6bc0b8c9-0758-4cd5-be54-c0b12cbbf7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description&quot;)</value>
      <webElementGuid>60e9116f-6994-4bb5-a067-463b62712e91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='description']</value>
      <webElementGuid>5465b089-7729-422e-800d-5b8c5812a47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='descripcion']/input</value>
      <webElementGuid>62462a56-ebd0-4762-a1a9-e2e7aae5ee6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>24e6d331-bc1a-49bc-9eb1-c9f1cb9d1449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'description' and @placeholder = '¿Por qué necesitan la visibilidad?' and @id = 'description']</value>
      <webElementGuid>59f13d88-7ae9-497d-ad4f-44f09cc4a966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
