<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go back</name>
   <tag></tag>
   <elementGuidId>89ca726d-32ff-4fbb-8f30-71a1ece96768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc3a3fd9-f77a-4346-afbe-066664359cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-5 text-indigo-500 hover:underline dark:text-white focus:outline-none</value>
      <webElementGuid>72f7e45f-6a18-429c-940a-b9584cb78164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go back</value>
      <webElementGuid>92972bf1-fde5-42a8-86ca-93fbc08ab3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex justify-center h-screen bg-white dark:bg-transparent&quot;]/div[@class=&quot;flex flex-col items-center justify-center text-center rounded-md&quot;]/div[@class=&quot;text-center&quot;]/button[@class=&quot;mt-5 text-indigo-500 hover:underline dark:text-white focus:outline-none&quot;]</value>
      <webElementGuid>0921fcd5-50a4-4cf4-bfa3-df96043b7a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/button</value>
      <webElementGuid>36a42364-3c3c-4bdc-bb8c-f1521dd84298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form submitted successfully!'])[1]/following::button[1]</value>
      <webElementGuid>acc8991d-a750-4d56-8a5f-18c7fc21fe9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web3Forms'])[1]/preceding::button[1]</value>
      <webElementGuid>de6060a5-ef56-4efa-96a5-11c9b20695c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go back']/parent::*</value>
      <webElementGuid>099543a9-490a-4aee-9b50-502d17ea80e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ddfdc564-df52-4b2a-a1f9-55892957b6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Go back' or . = 'Go back')]</value>
      <webElementGuid>7d60d340-19f2-4a75-9fb2-9d9dcf40bee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
