<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Form submitted successfully</name>
   <tag></tag>
   <elementGuidId>8aefbba8-3307-4823-8629-cdaf1d6d9401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>b1d663f5-daf8-422a-b21e-6e1e59e3fe36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-2xl text-green-500 dark:text-green-300 pt-7</value>
      <webElementGuid>7ae2fc22-3cb5-4f1a-a50c-0e4ecc18bed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form submitted successfully!</value>
      <webElementGuid>443c2867-ceaf-4130-9b97-08f0b43a9358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex justify-center h-screen bg-white dark:bg-transparent&quot;]/div[@class=&quot;flex flex-col items-center justify-center text-center rounded-md&quot;]/h3[@class=&quot;text-2xl text-green-500 dark:text-green-300 pt-7&quot;]</value>
      <webElementGuid>01721985-665d-4b51-9663-91ed6b62f6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/h3</value>
      <webElementGuid>881b3381-7753-4219-b8f3-e2f48fe36f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back'])[1]/preceding::h3[1]</value>
      <webElementGuid>b84c326e-ca5d-4098-9b46-630b1f382b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Form submitted successfully!']/parent::*</value>
      <webElementGuid>b9f75842-8eb8-4bc6-a03b-d8ad9e1c1cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>baa9c8fd-009f-419e-a9b5-f851c55d4d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Form submitted successfully!' or . = 'Form submitted successfully!')]</value>
      <webElementGuid>a746efc1-a63b-434c-b5bd-a98ad23b0379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
